env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
before:
  hooks:
    - go mod download
builds:
  - main: helmlinter/main.go
    binary: helmlinter
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archive:
  format: tar.gz
  files:
    - LICENSE
    - plugin.yaml
checksum:
  name_template: 'checksums.txt'
