builds:
  - main: ./cmd/helmlinter
    binary: ./bin/helmlinter
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOPROXY=https://gocenter.io
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

archive:
  format: tar.gz
  files:
    - LICENSE
    - plugin.yaml
