project_name: helm-linter
builds:
  - main: helmlinter/main.go
    binary: helmlinter
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOPROXY=https://gocenter.io
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

archive:
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - plugin.yaml
checksum:
  name_template: 'checksums.txt'
