builds:
  - main: ./cmd/helmlogin
    binary: ./bin/helmlogin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

archive:
  format: tar.gz
  files:
    - LICENSE
    - plugin.yaml
