name: "linter"
version: "0.1.1"
usage: "Please see https://github.com/rimusz/helm-linter for usage"
description: "Helm plugin to find hardcoded passwords in values.yaml files"
command: "$HELM_PLUGIN_DIR/bin/helmlinter"
downloaders:
- command: "bin/helmlinter"
useTunnel: false
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
