version: 2
jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint
          command: |
            shellcheck -x scripts/build.sh
            shellcheck -x scripts/tag.sh
            shellcheck -x scripts/install_plugin.sh
  build:
    docker:
      - image: golang:1.12.1-alpine3.9
    working_directory: /go/src/github.com/rimusz/helm-linter/cmd
    steps:
      - run:
          name: Install tools
          command: |
            apk add bash build-base ca-certificates curl git openssh
            curl -SLO https://github.com/goreleaser/goreleaser/releases/download/v0.103.1/goreleaser_Linux_x86_64.tar.gz
            mkdir -p /usr/local/goreleaser
            tar -xzf goreleaser_Linux_x86_64.tar.gz -C /usr/local/goreleaser
            ln -s /usr/local/goreleaser/goreleaser /usr/local/bin/goreleaser
            rm -rf goreleaser_Linux_x86_64.tar.gz
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - checkout
      - run:
          name: gofmt
          command: |
            gofmt -w -s . && git diff --exit-code
      - run:
          name: Build
          command: |
            set -e
            set -u

            if [[ -z "${CIRCLE_TAG:-}" ]]; then
              echo "Building snapshot..."
              scripts/build.sh
            else
              echo "Building release $CIRCLE_TAG..."
              scripts/build.sh --release
            fi
workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - build
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
